### ISSUE TITLE
Pip install not working for sensirion_i2c_lps22

### ISSUE THREAD

**Issue by mishave** [Sensirion/python-i2c-lps22#1]
Command:
'pip install sensirion_i2c_lps22
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement sensirion_i2c_lps22 (from versions: none)
ERROR: No matching distribution found for sensirion_i2c_lps22'

installing on RPI5 as per https://sensirion.github.io/python-i2c-lps22/installation.html

**Comment by mishave** [comment]
Sorry, I should have added it - I'm able to manually download from GitHub and install directly with 'pip install .'

**Comment by quentin-cy** [comment]
Hello @mishave 

Sorry about that, it seems we never actually published it to PyPi :(
We will that as soon as we have a moment 

Thanks for reporting it
Quentin

**Comment by psachs** [comment]
Library is now deployed to pypi
https://pypi.org/project/sensirion-i2c-lps22/
